services:
  db:
    image: postgres:13
    container_name: pgdb-lab1
    environment:
        POSTGRES_PASSWORD: root
        POSTGRES_USER: root
        POSTGRES_DB: ny_taxi
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
        - "5432:5432"
  jupyter:
    image: jupyter/datascience-notebook:latest
    container_name: jupyter-lab1
    ports:
      - "7979:8888"
    volumes:
      - ".:/home/jovyan/work:rw"
#    depends_on:
#      - pgdatabase
    command: >
      bash -c "pip install psycopg2-binary
      && pip install pyarrow
      && start-notebook.sh --NotebookApp.token=''"
